// Generated by gencpp from file qr_robot_localization/Location.msg
// DO NOT EDIT!


#ifndef QR_ROBOT_LOCALIZATION_MESSAGE_LOCATION_H
#define QR_ROBOT_LOCALIZATION_MESSAGE_LOCATION_H

#include <ros/service_traits.h>


#include <qr_robot_localization/LocationRequest.h>
#include <qr_robot_localization/LocationResponse.h>


namespace qr_robot_localization
{

struct Location
{

typedef LocationRequest Request;
typedef LocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Location
} // namespace qr_robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qr_robot_localization::Location > {
  static const char* value()
  {
    return "a94c40e70a4b82863e6e52ec16732447";
  }

  static const char* value(const ::qr_robot_localization::Location&) { return value(); }
};

template<>
struct DataType< ::qr_robot_localization::Location > {
  static const char* value()
  {
    return "qr_robot_localization/Location";
  }

  static const char* value(const ::qr_robot_localization::Location&) { return value(); }
};


// service_traits::MD5Sum< ::qr_robot_localization::LocationRequest> should match 
// service_traits::MD5Sum< ::qr_robot_localization::Location > 
template<>
struct MD5Sum< ::qr_robot_localization::LocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qr_robot_localization::Location >::value();
  }
  static const char* value(const ::qr_robot_localization::LocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_robot_localization::LocationRequest> should match 
// service_traits::DataType< ::qr_robot_localization::Location > 
template<>
struct DataType< ::qr_robot_localization::LocationRequest>
{
  static const char* value()
  {
    return DataType< ::qr_robot_localization::Location >::value();
  }
  static const char* value(const ::qr_robot_localization::LocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qr_robot_localization::LocationResponse> should match 
// service_traits::MD5Sum< ::qr_robot_localization::Location > 
template<>
struct MD5Sum< ::qr_robot_localization::LocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qr_robot_localization::Location >::value();
  }
  static const char* value(const ::qr_robot_localization::LocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_robot_localization::LocationResponse> should match 
// service_traits::DataType< ::qr_robot_localization::Location > 
template<>
struct DataType< ::qr_robot_localization::LocationResponse>
{
  static const char* value()
  {
    return DataType< ::qr_robot_localization::Location >::value();
  }
  static const char* value(const ::qr_robot_localization::LocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QR_ROBOT_LOCALIZATION_MESSAGE_LOCATION_H
