// Generated by gencpp from file qr_robot_control/Dijkstra.msg
// DO NOT EDIT!


#ifndef QR_ROBOT_CONTROL_MESSAGE_DIJKSTRA_H
#define QR_ROBOT_CONTROL_MESSAGE_DIJKSTRA_H

#include <ros/service_traits.h>


#include <qr_robot_control/DijkstraRequest.h>
#include <qr_robot_control/DijkstraResponse.h>


namespace qr_robot_control
{

struct Dijkstra
{

typedef DijkstraRequest Request;
typedef DijkstraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dijkstra
} // namespace qr_robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qr_robot_control::Dijkstra > {
  static const char* value()
  {
    return "a94c40e70a4b82863e6e52ec16732447";
  }

  static const char* value(const ::qr_robot_control::Dijkstra&) { return value(); }
};

template<>
struct DataType< ::qr_robot_control::Dijkstra > {
  static const char* value()
  {
    return "qr_robot_control/Dijkstra";
  }

  static const char* value(const ::qr_robot_control::Dijkstra&) { return value(); }
};


// service_traits::MD5Sum< ::qr_robot_control::DijkstraRequest> should match 
// service_traits::MD5Sum< ::qr_robot_control::Dijkstra > 
template<>
struct MD5Sum< ::qr_robot_control::DijkstraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qr_robot_control::Dijkstra >::value();
  }
  static const char* value(const ::qr_robot_control::DijkstraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_robot_control::DijkstraRequest> should match 
// service_traits::DataType< ::qr_robot_control::Dijkstra > 
template<>
struct DataType< ::qr_robot_control::DijkstraRequest>
{
  static const char* value()
  {
    return DataType< ::qr_robot_control::Dijkstra >::value();
  }
  static const char* value(const ::qr_robot_control::DijkstraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qr_robot_control::DijkstraResponse> should match 
// service_traits::MD5Sum< ::qr_robot_control::Dijkstra > 
template<>
struct MD5Sum< ::qr_robot_control::DijkstraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qr_robot_control::Dijkstra >::value();
  }
  static const char* value(const ::qr_robot_control::DijkstraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_robot_control::DijkstraResponse> should match 
// service_traits::DataType< ::qr_robot_control::Dijkstra > 
template<>
struct DataType< ::qr_robot_control::DijkstraResponse>
{
  static const char* value()
  {
    return DataType< ::qr_robot_control::Dijkstra >::value();
  }
  static const char* value(const ::qr_robot_control::DijkstraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QR_ROBOT_CONTROL_MESSAGE_DIJKSTRA_H
