// Generated by gencpp from file qr_robot_control/qr_robot_control.msg
// DO NOT EDIT!


#ifndef QR_ROBOT_CONTROL_MESSAGE_QR_ROBOT_CONTROL_H
#define QR_ROBOT_CONTROL_MESSAGE_QR_ROBOT_CONTROL_H

#include <ros/service_traits.h>


#include <qr_robot_control/qr_robot_controlRequest.h>
#include <qr_robot_control/qr_robot_controlResponse.h>


namespace qr_robot_control
{

struct qr_robot_control
{

typedef qr_robot_controlRequest Request;
typedef qr_robot_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct qr_robot_control
} // namespace qr_robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qr_robot_control::qr_robot_control > {
  static const char* value()
  {
    return "c9caccfcada3b6a45d8528a23bccaf1a";
  }

  static const char* value(const ::qr_robot_control::qr_robot_control&) { return value(); }
};

template<>
struct DataType< ::qr_robot_control::qr_robot_control > {
  static const char* value()
  {
    return "qr_robot_control/qr_robot_control";
  }

  static const char* value(const ::qr_robot_control::qr_robot_control&) { return value(); }
};


// service_traits::MD5Sum< ::qr_robot_control::qr_robot_controlRequest> should match 
// service_traits::MD5Sum< ::qr_robot_control::qr_robot_control > 
template<>
struct MD5Sum< ::qr_robot_control::qr_robot_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qr_robot_control::qr_robot_control >::value();
  }
  static const char* value(const ::qr_robot_control::qr_robot_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_robot_control::qr_robot_controlRequest> should match 
// service_traits::DataType< ::qr_robot_control::qr_robot_control > 
template<>
struct DataType< ::qr_robot_control::qr_robot_controlRequest>
{
  static const char* value()
  {
    return DataType< ::qr_robot_control::qr_robot_control >::value();
  }
  static const char* value(const ::qr_robot_control::qr_robot_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qr_robot_control::qr_robot_controlResponse> should match 
// service_traits::MD5Sum< ::qr_robot_control::qr_robot_control > 
template<>
struct MD5Sum< ::qr_robot_control::qr_robot_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qr_robot_control::qr_robot_control >::value();
  }
  static const char* value(const ::qr_robot_control::qr_robot_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_robot_control::qr_robot_controlResponse> should match 
// service_traits::DataType< ::qr_robot_control::qr_robot_control > 
template<>
struct DataType< ::qr_robot_control::qr_robot_controlResponse>
{
  static const char* value()
  {
    return DataType< ::qr_robot_control::qr_robot_control >::value();
  }
  static const char* value(const ::qr_robot_control::qr_robot_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QR_ROBOT_CONTROL_MESSAGE_QR_ROBOT_CONTROL_H
